# ملف .streamlit/secrets.toml

# قسم Alpha Vantage API
[alpha_vantage]
api_key = "S6G0CLDFPAW2NKNA"  # مفتاح مثال - استبدله بمفتاحك الخاص
api_url = "https://www.alphavantage.co/query"
rate_limit = "5 requests per minute"

# قسم NewsAPI
[news_api]
api_key = "f55929edb5ee471791a1e622332ff6d8"  # مفتاح مثال - استبدله بمفتاحك الخاص
sources = "bloomberg,cnbc,reuters"
language = "ar"
# قسم twelvedataAPI
[twelvedata]
api_key = "892f28628ea14be189ae98c007587b3a"
# إعدادات التطبيق
[app_settings]
refresh_interval = 3600  # ثانية (ساعة واحدة)
max_data_points = 1000
debug_mode = false

[ui_settings]
theme = "light"
language = "ar"
timezone = "Asia/Riyadh"
