# ملف secrets.toml - لتخزين البيانات السرية للتطبيق

# قسم Alpha Vantage API (للسوق الأمريكي)
[alpha_vantage]
api_key = "YOUR_ALPHA_VANTAGE_API_KEY"  # احصل على مفتاح من https://www.alphavantage.co/support/#api-key
api_url = "https://www.alphavantage.co/query"
rate_limit = "5 requests per minute"    # الحد المجاني لطلبات API

# قسم Tadawul API (للسوق السعودي)
[tadawul]
api_key = "YOUR_TADAWUL_API_KEY"       # إذا كان لديك وصول لواجهة تداول
api_url = "https://api.tadawul.com.sa"
sandbox_mode = true                    # وضع الاختبار (true/false)

# قسم NewsAPI (للأخبار الاقتصادية)
[news_api]
api_key = "YOUR_NEWS_API_KEY"          # احصل على مفتاح من https://newsapi.org/
sources = "bloomberg,cnbc,reuters"    # المصادر المفضلة
language = "ar"                        # اللغة العربية

# إعدادات قاعدة البيانات (اختياري)
[database]
db_host = "localhost"
db_name = "market_data"
db_user = "admin"
db_password = "secure_password_here"
db_port = 5432

# إعدادات التطبيق العامة
[app_settings]
default_market = "saudi"               # السوق الافتراضي عند التشغيل
refresh_interval = 3600                # وقت تحديث البيانات بالثواني (ساعة)
max_data_points = 1000                 # الحد الأقصى لنقاط البيانات المسجلة
debug_mode = false                     # وضع تصحيح الأخطاء

# إعدادات واجهة المستخدم
[ui_settings]
theme = "light"                        # أو "dark"
language = "ar"                        # اللغة العربية
timezone = "Asia/Riyadh"               # التوقيت المحلي
