[Alpha_vantage]
api_key = "9U23G0RQSOHBTLON"
api_url = "https://www.alphavantage.co/query"
rate_limit = "5 requests per minute"


[news_api]
api_key = "f55929edb5ee471791a1e622332ff6d8"  
sources = "bloomberg,cnbc,reuters"
language = "ar"

[twelvedata]
api_key = "892f28628ea14be189ae98c007587b3a"

[app_settings]
refresh_interval = 3600  
max_data_points = 1000
debug_mode = false

[ui_settings]
theme = "light"
language = "ar"
timezone = "Asia/Riyadh"
